# Generated by Django 3.2.21 on 2023-11-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy_table',
            name='premium',
        ),
        migrations.CreateModel(
            name='Premium_Details_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minage', models.CharField(max_length=500)),
                ('maxage', models.CharField(max_length=500)),
                ('premium_amount', models.BigIntegerField()),
                ('POLICY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.policy_table')),
            ],
        ),
    ]
