# Generated by Django 3.2.21 on 2023-11-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_auto_20231122_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_premium_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('premium_amount', models.BigIntegerField()),
                ('POLICY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.policy_table')),
            ],
        ),
    ]
